import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { DataContextProvider } from "@/context/DataContext";

const dm = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <DataContextProvider>
        <html lang="en">
          <body className={dm.className}>{children}</body>
        </html>
      </DataContextProvider>
    </SessionProvider>
  );
}
